{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allure.py:10: AssertionError"}, "description": "this test fails", "start": 1586002828855, "stop": 1586002828855, "uuid": "6e10aa6a-2a7d-4158-824f-d96d94c59fad", "historyId": "b2873979f94e50b7249573af844598f1", "testCaseId": "924c4ecc2b1e866f13aa32d5ad57625b", "fullName": "test_allure#test_failure", "labels": [{"name": "suite", "value": "test_allure"}, {"name": "host", "value": "Tony-Mac-Pro.local"}, {"name": "thread", "value": "26850-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}